### ISSUE TITLE
Small spam of Anvil event fired for side SERVER in log

### ISSUE THREAD

**Issue by Insane96** [LumberWizard/Anvil-Patch#1]
`[22:12:33] [Server thread/INFO] [anvilpatch]: Anvil event fired for side SERVER`

**Comment by LumberWizard** [comment]
Fixed by https://github.com/LumberWizard/Anvil-Patch/commit/2e60f1a2c45184d588f87016553b03e1a9999841. Release should be up on CurseForge soon.
