### ISSUE TITLE
Suggestion: Anvil Damage Config

### ISSUE THREAD

**Issue by IdrisQe** [LumberWizard/Anvil-Patch#2]
This may be beyond the expected scope of the mod, but given this is meant to be a less-invasive version of Anvil Fix, and Anvil Fix has (semi-)recently added the ability to disable Anvil damage, I feel this is a reasonable request.

Many people, myself included, can't stand the Anvil damage mechanics, since each Anvil costs 31 Iron Ingots, and may break after only 3 uses if you're unlucky.
It'd be really nice to be able to configure the chance of an anvil taking damage, or disable it outright.
Perhaps also having seperate configs for different "sources" if possible, such as:
-Damage chance on repair using Anvil
-Damage chance on enchant using Anvil
-Damage chance on falling (Anvil entity falling)
With 0 in any of these disabling damage from that entirely.
That way you could make repairing and enchanting using anvils never damage them, but could still damage an anvil by dropping it on things if a mod required a damaged anvil in a crafting recipe or something. Or make enchanting an item with an anvil be riskier than repairing. Etc.

**Comment by LumberWizard** [comment]
Necro time! Having more granular control over it seems possible, but it's a bunch of logic to implement, so I'm not sure I'll look at it for 1.12. Maybe if I decide to update it to later versions, I'll reconsider!
