### ISSUE TITLE
ENCHANTMENT_ONLY setting not working correctly

### ISSUE THREAD

**Issue by KirikaAetheria** [LumberWizard/Anvil-Patch#3]
Good day. I'd like to report a bug which happens consistently in a small server I'm currently hosting. We are using the ENCHANTMENT_ONLY value in anvilpatch's cfg file, which from my understanding should keep repairs costing the same as they initially did regardless of how many times an item is enchanted. Despite this, repair costs will go up in items which have been enchanted. This happens consistently in all items I have checked:

-Using armor from one of the mods, Ice and Fire, Protection 4 + Unbreaking 3 vs no enchantments
![enchantments](https://user-images.githubusercontent.com/61053558/74538185-90d49a00-4f33-11ea-926d-47c5ee46637c.png)
![no enchantments](https://user-images.githubusercontent.com/61053558/74538192-94682100-4f33-11ea-8a47-a264025ef5eb.png)

-Using vanilla armor, Protection 4 + Unbreaking 3 vs no enchantments
![enchantments 2](https://user-images.githubusercontent.com/61053558/74538220-a34ed380-4f33-11ea-9a54-b6b54f4f59c6.png)
![no enchantments 2](https://user-images.githubusercontent.com/61053558/74538225-a5189700-4f33-11ea-8cec-3a7840a821a8.png)

Here is the current server installation I am using, in case you would like to test it yourself - https://drive.google.com/file/d/1Iz3xRBHuivIrtucbMpRNMQ_pGhm2ZAOk/view . Also, if there's any testing you'd like me to do on my end since everything is set up already, do let me know and I'll be more than happy to assist you.

Thank you very much for your time

**Comment by LumberWizard** [comment]
Great catch! Sorry for taking 11 months to notice your issue (on the day! Wow). Fixed in dev, will upload tomorrow.
