### ISSUE TITLE
Quark Runes unusable

### ISSUE THREAD

**Issue by SenZ01** [LumberWizard/Anvil-Patch#4]
Good evening, Quark Runes are Unusable when Anvil Patch is installed.

You should be able to Put the Runes on any enchanted item to Change the Color of the Enchantment Glimmer, but it dosn't give any output in the Anvil.

Works fine without Anvil Fix.

**Comment by SenZ01** [comment]
AnvilFix-1.12.2-1.0.5

**Comment by LumberWizard** [comment]
Can't reproduce; are you applying it to an enchanted item?

**Comment by LumberWizard** [comment]
You are using https://www.curseforge.com/minecraft/mc-mods/anvil-fix
My mod is https://www.curseforge.com/minecraft/mc-mods/anvil-patch-lawful
