### ISSUE TITLE
Add config option to allow going beyond vanilla enchantment level caps.

### ISSUE THREAD

**Issue by paul23-git** [LumberWizard/Anvil-Patch#6]
I might be misunderstanding this mod a bit, but with an anvil I have a power 8 book and a bow - yet the result is still a power 5 bow.

**Comment by LumberWizard** [comment]
The mod doesn't change the logic for the enchantments themselves. Specifically what's happening is [this line](https://github.com/LumberWizard/Anvil-Patch/blob/f38f53675d7fef265275550a5c9982ef5daee165/src/main/java/lumberwizard/anvilpatch/common/AnvilEventHandler.java#L104) setting the enchantment back to its max level, which is the same thing vanilla does. I could add a config option to disable that check.

**Comment by paul23-git** [comment]
It means it won't work with mods that allow for higher level enchantments like apotheosis, so for compatibility it should be there I think.

**Comment by LumberWizard** [comment]
I added it, you should see it on CurseForge soon.
