### ISSUE TITLE
feature request - destroy items that don't have durability

### ISSUE THREAD

**Issue by Shivaxi** [LumberWizard/Anvil-Patch#7]
One of the things I'd love is an option to allow the destruction of items that don't usually have a durability bar, such as enchanted books.  I use this so that users can only rip off enchants 1 at a time from tools and such, and in the process, destroy the item.  However since enchanted books of course don't have or use durability, they can pull off every single enchantment from said enchanted book.

p.s. i also saw the issue about the anvil saying "too expensive" instead of the proper levels haha, would be great to see that fixed too tho I know that one is probably a doozy given minecraft's incredible GUI rendering code =P

**Comment by LumberWizard** [comment]
What do you mean? Vanilla behavior is "apply all enchantments from the right item to the left one, then destroy the right item"; what mod are you using to change it?

**Comment by Shivaxi** [comment]
I am so sorry, been a long night and I got my mods mixed up haha, this was a report meant for the Disenchanter mod, not Anvil Patch, my bad.

The only thing I was curious about with Anvil Patch is having the anvil tell you the correct levels needed to apply something rather than saying "too expensive" but I saw that was already reported.
