### ISSUE TITLE
The mod works good, but i cant se the level requiered

### ISSUE THREAD

**Issue by kriticalvinho** [LumberWizard/Anvil-Patch#8]
Hi, im using your mod in my Spongeforge server, the mod works but the "is very expensive" on the anvil stills appear what can i do?

**Comment by LumberWizard** [comment]
It's a known issue. Unfortunately there's not much I can do about it using Forge, and I won't bother with coremodding it.

**Comment by kriticalvinho** [comment]
Ok dont worry if you found how to fix It Tell me please, thanks you for the answer!
