### ISSUE TITLE
"Allow repairs beyond ench cap" allows players to create enchs beyond cap

### ISSUE THREAD

**Issue by democat3457** [LumberWizard/Anvil-Patch#9]
Despite what the config comment says, the configuration option `B:"Allow repairs beyond enchantment level cap."` does actually allow players to craft exactly one enchantment above the enchantment's cap. 

To test this, I turned the flag on, and I observed that I was able to craft a Sharp VI book from two Sharp Vs. I then turned the flag off, and I noticed that I was no longer able to craft a Sharp VI book, but it was still possible to apply Sharp VI to an unenchanted item. (also yeah the bug it was supposed to fix still worked as expected - flag off -> (Sharp VI item + Sharp V book = Sharp V item), flag on -> (... = Sharp VI item))

Using anvilpatch 1.1.0.

**Comment by LumberWizard** [comment]
Good catch! I'll push a fix within the next couple of days if I remember, otherwise respond to this issue again to remind me.

**Comment by democat3457** [comment]
bump

**Comment by democat3457** [comment]
Just got around to testing this, and it seems to work nicely! Thanks!
